name: SAC
device: cuda:0
discount: 0.99
reward_scale: 1
n_seed_steps: 1000

actor_lr: 1e-4  
critic_lr: 1e-4 #changed actor/critic learning rates to from 1e-4 to 3e-4 like edoardo
#
alpha_lr: 1e-4
soft_target_tau: 0.005 #was 0.005
learnable_temperature: True
init_temperature: 0.1
clip_obs: 200
norm_clip: 5
norm_eps: 0.01
hidden_dim: 256  #dont change
use_data_parallel: False  # DataParallel incompatible with RL distributions
sampler:
  type: her
  strategy: future
  k: 4
update_epoch: 1  # 1 update per episode (50 steps) for faster training